### ISSUE TITLE
New facility for loop issues

### ISSUE THREAD

**Issue by freecitiesdev** [Free-Cities/Free-Cities#338] opened 2017-04-27 21:35 UTC
Getting occasional "cannot read property.ID of undefined" for <<if _ID != $slaves[_i].ID>> in the new facility for loops.

Example:
[free-cities-20170427-101503.zip](https://github.com/Free-Cities/Free-Cities/files/962991/free-cities-20170427-101503.zip)

Can anyone who worked on those loops take a look?

**Comment by Bane70** [comment] 2017-04-27 21:58
OK. I know what's happening. I'll have it corrected in a few minutes.

**Comment by Bane70** [comment] 2017-04-28 00:57
Ok. I figured out the problem will update in a bit as it can/will affect all facilities.

**Comment by fcpmanon** [comment] 2017-04-29 14:29
My current pending merge addresses some bugs that can cause slaves to be reassigned from facilities jobs without removing them from the facilities array

I've noticed that some slaves change IDs from week to week as well, even without selling/discarding any - I haven't figured out what causes the re-ordering though

**Comment by fcpmanon** [comment] 2017-04-29 14:31
The undefined error here could also be caused by one of the slave objects in the slaves array becoming null

Might be better to use ndef $slaves[ i ] instead of i < _SL for the facilities ID loops.

**Comment by Bane70** [comment] 2017-04-29 18:30
>assignJob widget can now be used for non-facilities assignments
Ah this looks like it does more or less what I was intending to do eventually, but my time to code or even play/test is limited lately.

>I've noticed that some slaves change IDs from week to week as well, even without selling/discarding any - I haven't figured out what causes the re-ordering though
I assume you mean the array index # of the slave changes from week to week? As the .ID as far as I know should never change except for a NG+. Buying slaves can change the .Index # as well, so can the constant sorting from Main.tw especially if sorting by devotion.

>The undefined error here could also be caused by one of the slave objects in the slaves array becoming null
If the array has a Null slave then that would probably be causing other problems as well and would be better to find what is causing null slaves in the array than placing a bandaid here. I've not yet seen a null in the $slaves array, unless I myself accidentally created it.
Alpha releases are supposed to be a time to find and fix bugs not apply bandaids, to hide errors.

**Comment by fcpmanon** [comment] 2017-04-30 05:12
Er, yes, I meant the index changes, not the ID.  Sorting from Main.tw would explain it.

**Comment by fcpmanon** [comment] 2017-04-30 05:42
Note that my revised removeJob widget is still insufficient by itself for safe  retrieval from agent assignment

I started looking at agentRetrieve with the idea of moving it into a widget and calling it from removeJob, but it currently expects $currentArcology to be set, and I haven't explored the agent/neighbor code enough yet to know how to find that reliably otherwise

Normally players shouldn't be able to do anything to the agent other than retrieve them using the neighbor relations screen, but I'd like to handle it properly anyway, just in case -- for example, an RA reassignment rule applied to specific slave (agent) could trigger removeJob while bypassing agentRetrieve

**Comment by fcpmanon** [comment] 2017-05-01 09:14
Actually the agent removal via RA concern mentioned above already is prevented by this code in raWidgets:

<<if $args[0].assignmentVisible != 1>>
	<<set _exclude = true>>
<</if>>

That prevents all slaves in facilities or other non-visible assignments from being reassigned by the RA.  Which explains why those types of rules never worked for me.

I plan to submit a fairly large RA revision over the next few days.

**Comment by fcpmanon** [comment] 2017-05-02 05:56
#357 addresses the issues discussed above by continuing to block RA application to agents or agent companions while on assignment.  Widgetizing agentRetrieve remains a to-do item.

**Comment by fcpmanon** [comment] 2017-05-11 08:37
with #441 I think my concerns about agents have been put to rest

**Closed** 2017-05-11 21:02 UTC
