### ISSUE TITLE
Head girl priorities

### ISSUE THREAD

**Issue by buttwhy** [Free-Cities/Free-Cities#837] opened 2017-07-12 16:16 UTC
I think the head girl's priorities are maybe in the opposite order? Or at the very least, not in the order that's indicated on the page. The page implies that the order will be, from most important to least important, Health, Flaws, Paraphilias, Obedience, Skills. However in the game, the HG would train skills before dealing with flaws. 

Is this intended?

**Comment by kopareigns** [comment] 2017-07-12 17:31
I'm not sure how you're seeing skills training before flaws unless you temporarily barred your head girl from dealing with flaws. The priority order is Health, Paraphilia removal, Sexual Flaw removal, Behavioral Flaw removal, Behavioral Flaw softening, Sexual Flaw softening, Obedience, Oral training, Vaginal training, Anal training, Whore training, Entertainment training.

This is currently hard-coded into the game with no way for the player to change the order. That being said, it would be a nice addition if we could modify the priority order. I'll think about it and see if I can't come up with a half decent way to add that myself. Others are free to beat me to it if they feel like it.

**Comment by buttwhy** [comment] 2017-07-12 18:58
I don't know. I've tried turning it all off and on again, and I'm still getting my HG training skills when there are flaws on other girls to be fixed.

**Comment by kopareigns** [comment] 2017-07-12 19:41
Oh I see what you mean now. That happens because the head girl prioritizes slaves based on the way the $slaves array is sorted (default is by devotion, decreasing order). So your head girl will prioritize more devoted slaves first. You can change the sorting in the Summary Options page. However this will change the order in which your slaves are displayed too. If it's sorted differently when you click Next Week, the head girl will end up prioritizing different slaves.

On an individual slave, the priority order is what I stated above, but slaves are first chosen based on the sorting choice. For now, the ability to change this is not implemented.

**Comment by buttwhy** [comment] 2017-07-12 19:46
Oh! Ok, I see. I thought the priority was for all the girls, not on an individual-basis. Thanks, that makes more sense now. Should I close this issue, then?

**Comment by kopareigns** [comment] 2017-07-12 21:34
I guess? Strictly speaking what you've described is the way the game was designed, and is intended so your initial question was answered. On the other hand if you think it would be better if it were changed you could have it as a suggestion. If you feel that way maybe just close it and open a new one as a suggestion?

**Closed** 2017-07-12 23:47 UTC
